version: '4.30.0'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/fin_uni_it_blog-main
    depends_on:
      - db


  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'blog'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
